### ISSUE TITLE
suggest

### ISSUE THREAD

**Issue by JZFamily** [JZFamily/WeatherInfoProject#4]
首先，这么快出成果，令人惊讶。
1，能不能加一个侧边栏提供对图标样式的选择呢，可以通过点击显示折线，饼图，柱状图。
2，大小需要自适应，在我的笔记本上，显得稍大。

**Comment by Yaktsar-0619** [comment]
窗口其他部件自适应倒是很简单，js就不可以

**Comment by Yaktsar-0619** [comment]
因为js不适用css规则

**Comment by Yaktsar-0619** [comment]
与其一个适应一个不适应，还不如将全体文字和统计图靠左发展

**Comment by JZFamily** [comment]
@233mc44 
我记得可以居中，然后让div的大小设置为浏览器窗口的某个比例

**Comment by Yaktsar-0619** [comment]
那是让文字居中，不对js模块有效

**Comment by JZFamily** [comment]
@233mc44 
 i have set the auto size by css.

**Comment by Yaktsar-0619** [comment]
...
